### ISSUE TITLE
Merging colormaps "Docs Issue"

### ISSUE THREAD

**Issue by pratiman-91** [lukelbd/proplot#202]
### Description

Merging colormaps in the docs (https://proplot.readthedocs.io/en/latest/colormaps.html) not working as expected.

### Steps to reproduce

```python
import proplot as plot
import numpy as np
state = np.random.RandomState(51423)
data = state.rand(30, 30).cumsum(axis=1)

# Generate figure
fig, axs = plot.subplots([[0, 1, 1, 0], [2, 2, 3, 3]], axwidth=2.4, span=False)
axs.format(
    xlabel='xlabel', ylabel='ylabel',
    suptitle='Merging existing colormaps'
)

# Diverging colormap example
title1 = 'Custom diverging map'
cmap1 = plot.Colormap('Blues4_r', 'Reds3', name='Diverging', save=True)

# SciVisColor examples
title2 = 'SciVisColor example with equal ratios'
cmap2 = plot.Colormap(
    'Greens1_r', 'Oranges1', 'Blues1_r', 'Blues6',
    name='SciVisColorEqual', save=True
)
title3 = 'SciVisColor example'
cmap3 = plot.Colormap(
    'Greens1_r', 'Oranges1', 'Blues1_r', 'Blues6',
    ratios=(1, 3, 5, 10), name='SciVisColor', save=True
)

# Plot examples
for ax, cmap, title in zip(axs, (cmap1, cmap2, cmap3), (title1, title2, title3)):
    m = ax.pcolormesh(data, cmap=cmap, levels=500)
    ax.colorbar(m, loc='b', locator='null', label=cmap.name)
    ax.format(title=title)
```

**Expected behavior**: [What you expected to happen]

Saved colormap to '/home/docs/.proplot/cmaps/Diverging.json'.
Saved colormap to '/home/docs/.proplot/cmaps/SciVisColorEqual.json'.
Saved colormap to '/home/docs/.proplot/cmaps/SciVisColor.json'.

https://proplot.readthedocs.io/en/latest/_images/colormaps_9_1.svg

**Actual behavior**: [What actually happened]
```python
File "C:\ProgramData\Miniconda3\lib\site-packages\proplot\utils.py", line 427, in to_rgba
    *color, opacity = mcolors.to_rgba(color)  # ensure is valid color

  File "C:\ProgramData\Miniconda3\lib\site-packages\matplotlib\colors.py", line 185, in to_rgba
    rgba = _to_rgba_no_colorcycle(c, alpha)

  File "C:\ProgramData\Miniconda3\lib\site-packages\matplotlib\colors.py", line 261, in _to_rgba_no_colorcycle
    raise ValueError(f"Invalid RGBA argument: {orig_c!r}")

ValueError: Invalid RGBA argument: 'Blues4'


During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "C:\ProgramData\Miniconda3\lib\site-packages\proplot\constructor.py", line 576, in Colormap
    color = to_rgba(arg, cycle=cycle)

  File "C:\ProgramData\Miniconda3\lib\site-packages\proplot\utils.py", line 429, in to_rgba
    raise ValueError(f'Invalid RGB argument {color!r}.')

ValueError: Invalid RGB argument 'Blues4'.


During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "C:\Users\WDAGUtilityAccount\.spyder-py3\temp.py", line 22, in <module>
    cmap1 = plot.Colormap('Blues4_r', 'Reds3', name='Diverging', save=True)

  File "C:\ProgramData\Miniconda3\lib\site-packages\proplot\constructor.py", line 585, in Colormap
    raise ValueError(message)

ValueError: Invalid colormap, color cycle, or color 'Blues4'. Valid names are: 'blues', 'brbg', 'bugn', 'bupu', 'cmrmap', 'gnbu', 'greens', 'greys', 'orrd', 'oranges', 'prgn', 'piyg', 'pubu', 'pubugn', 'puor', 'purd', 'purples', 'rdbu', 'rdgy', 'rdpu', 'rdylbu', 'rdylgn', 'reds', 'spectral', 'wistia', 'ylgn', 'ylgnbu', 'ylorbr', 'ylorrd', 'afmhot', 'autumn', 'binary', 'bone', 'brg', 'bwr', 'cool', 'coolwarm', 'copper', 'cubehelix', 'flag', 'gist_earth', 'gist_gray', 'gist_heat', 'gist_ncar', 'gist_rainbow', 'gist_stern', 'gist_yarg', 'gnuplot', 'gnuplot2', 'gray', 'hot', 'hsv', 'jet', 'nipy_spectral', 'ocean', 'pink', 'prism', 'rainbow', 'seismic', 'spring', 'summer', 'terrain', 'winter', 'accent', 'dark2', 'paired', 'pastel1', 'pastel2', 'set1', 'set2', 'set3', 'tab10', 'tab20', 'tab20b', 'tab20c', 'viridis', 'plasma', 'inferno', 'magma', 'cividis', 'twilight', 'acton', 'algae', 'amp', 'balance', 'bamako', 'batlow', 'berlin', 'bilbao', 'blue1', 'blue2', 'blue3', 'blue4', 'blue5', 'blue6', 'blue7', 'blue8', 'blue9', 'boreal', 'br', 'broc', 'broco', 'brown1', 'brown2', 'brown3', 'brown4', 'brown5', 'brown6', 'brown7', 'brown8', 'brown9', 'buda', 'coldhot', 'cork', 'corko', 'curl', 'davos', 'deep', 'delta', 'dense', 'devon', 'div', 'drywet', 'dusk', 'fire', 'glacial', 'green1', 'green2', 'green3', 'green4', 'green5', 'green6', 'green7', 'green8', 'haline', 'hawaii', 'ice', 'icefire', 'imola', 'lajolla', 'lapaz', 'lisbon', 'mako', 'marine', 'matter', 'mono', 'monocycle', 'negpos', 'nuuk', 'oleron', 'orange1', 'orange2', 'orange3', 'orange4', 'orange5', 'orange6', 'orange7', 'orange8', 'oslo', 'oxy', 'phase', 'redpurple1', 'redpurple2', 'redpurple3', 'redpurple4', 'redpurple5', 'redpurple6', 'redpurple7', 'redpurple8', 'rocket', 'roma', 'romao', 'solar', 'speed', 'stellar', 'sunrise', 'sunset', 'tempo', 'thermal', 'tofino', 'tokyo', 'turbid', 'turku', 'vik', 'viko', 'vlag', '538', 'bmh', 'classic', 'colorblind', 'colorblind10', 'default', 'flatui', 'ggplot', 'qual1', 'qual2', 'seaborn', 'tableau'.
```
**Possible Solution**: 
There is a change in the labels of the SciVisColors. This can be further applied to the change in the included cmaps in the docs.
```python
import proplot as plot
fig, axs = plot.show_cmaps()
```

In the case of the example provided use the following:
```python
import proplot as plot
import numpy as np
state = np.random.RandomState(51423)
data = state.rand(30, 30).cumsum(axis=1)

# Generate figure
fig, axs = plot.subplots([[0, 1, 1, 0], [2, 2, 3, 3]], axwidth=2.4, span=False)
axs.format(
    xlabel='xlabel', ylabel='ylabel',
    suptitle='Merging existing colormaps'
)

# Diverging colormap example
title1 = 'Custom diverging map'
cmap1 = plot.Colormap('blue4_r', 'redpurple3', name='Diverging', save=True) #change here

# SciVisColor examples
title2 = 'SciVisColor example with equal ratios'
cmap2 = plot.Colormap(
    'Green1_r', 'Orange1', 'Blue1_r', 'Blue6', #change here
    name='SciVisColorEqual', save=True
)
title3 = 'SciVisColor example'
cmap3 = plot.Colormap(
    'Green1_r', 'Orange1', 'Blue1_r', 'Blue6', #change here
    ratios=(1, 3, 5, 10), name='SciVisColor', save=True
)

# Plot examples
for ax, cmap, title in zip(axs, (cmap1, cmap2, cmap3), (title1, title2, title3)):
    m = ax.pcolormesh(data, cmap=cmap, levels=500)
    ax.colorbar(m, loc='b', locator='null', label=cmap.name)
    ax.format(title=title)
```
### Proplot version

Paste the result of `0.6.4` here.

**Comment by lukelbd** [comment]
Yep, in the upcoming version 0.7.0, I've made a backwards-incompatible change by renaming the SciVisColor colormaps (`Blue0`, `Blue1`, etc. to `Blues0`, `Blues1`, etc.) to prevent name clashes with the open-color colors (`blue0`, `blue1`, etc). Previously it was impossible to make monochromatic colormaps with "open-color" colors by calling `plot.Colormap('blue1')` because the SciVisColor colormaps were looked up instead. The examples in the "Latest" version of the documentation are updated to reflect this. For the older documentation you should select "v0.6.4" in the bottom left corner popup window.
