### ISSUE TITLE
Incompatible with matplotlib=3.5.0

### ISSUE THREAD

**Issue by zxdawn** [lukelbd/proplot#302]
### Description

`vmin` doesn't work with the new version (3.5.0) of matplotlib.

### Steps to reproduce

```python
import proplot as pplt
import numpy as np

state = np.random.RandomState(51423)
x = y = np.array([-10, -5, 0, 5, 10])
data = state.rand(y.size, x.size)

fig, axs = pplt.subplots()
axs.pcolormesh(x, y, data, vmin=0)
```

**Actual behavior**: [What actually happened]
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/public/home/zhangxin/new/miniconda3/envs/knmi_arctic_new/lib/python3.8/site-packages/proplot/internals/process.py", line 284, in _redirect_or_standardize
    return func(self, *args, **kwargs)  # call unbound method
  File "/public/home/zhangxin/new/miniconda3/envs/knmi_arctic_new/lib/python3.8/site-packages/proplot/axes/plot.py", line 3904, in pcolormesh
    kw = self._parse_cmap(x, y, z, to_centers=True, **kw)
  File "/public/home/zhangxin/new/miniconda3/envs/knmi_arctic_new/lib/python3.8/site-packages/proplot/internals/warnings.py", line 96, in _deprecate_kwargs
    return func_orig(*args, **kwargs)
  File "/public/home/zhangxin/new/miniconda3/envs/knmi_arctic_new/lib/python3.8/site-packages/proplot/axes/plot.py", line 2703, in _parse_cmap
    norm, cmap, kwargs = self._parse_discrete(
  File "/public/home/zhangxin/new/miniconda3/envs/knmi_arctic_new/lib/python3.8/site-packages/proplot/axes/plot.py", line 2529, in _parse_discrete
    norm = pcolors.DiscreteNorm(levels, norm=norm, unique=unique, step=step)
  File "/public/home/zhangxin/new/miniconda3/envs/knmi_arctic_new/lib/python3.8/site-packages/proplot/internals/warnings.py", line 96, in _deprecate_kwargs
    return func_orig(*args, **kwargs)
  File "/public/home/zhangxin/new/miniconda3/envs/knmi_arctic_new/lib/python3.8/site-packages/proplot/colors.py", line 2459, in __init__
    self.vmin = vmin
  File "/public/home/zhangxin/new/miniconda3/envs/knmi_arctic_new/lib/python3.8/site-packages/matplotlib/colors.py", line 1148, in vmin
    if value != self._vmin:
AttributeError: 'DiscreteNorm' object has no attribute '_vmin'
```

### Proplot version

Paste the results of `import matplotlib; print(matplotlib.__version__); import proplot; print(proplot.version)`here.
```
3.5.0
0.9.5
```

**Comment by lukelbd** [comment]
Thanks for the report. This was short-sighted design on my part -- long story short `DiscreteNorm.__init__()` now calls `Normalize.__init__(self)` instead of handling `vmin` and `vmax` internally. I also fixed a related issue that prevented drawing colorbars with `ScalarMappable`s scaled by `DiscreteNorm`.
